name: CI

on: [push, pull_request]

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  tools: cs2pr
            - name: "Install dependencies with composer"
              run: |
                  composer install --prefer-dist --no-progress --no-suggest
                  vendor/bin/simple-phpunit --version
            - name: "Run PHPStan"
              run: vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  tools: cs2pr
            - name: "Install dependencies with composer"
              run: composer install --prefer-dist --no-progress --no-suggest
            - name: "Run PHP-CS-Fixer"
              run: vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - php-version: 7.4
                      composer-flags: --prefer-stable --prefer-lowest
                    - php-version: 8.0
                      composer-flags: --prefer-stable --prefer-lowest
                    - php-version: 8.1
                      composer-flags: --prefer-stable --prefer-lowest
                    - php-version: 7.4
                      symfony-version: 4.4.*
                    - php-version: 8.0
                      symfony-version: 4.4.*
                    - php-version: 8.1
                      symfony-version: 4.4.*
                    - php-version: 7.4
                      symfony-version: 5.4.*
                    - php-version: 8.0
                      symfony-version: 5.4.*
                    - php-version: 8.1
                      symfony-version: 5.4.*
                    - php-version: 8.0
                      symfony-version: 6.0.*
                    - php-version: 8.1
                      symfony-version: 6.0.*
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}
            - name: "Install dependencies (fixed Symfony version) with composer"
              if: matrix.symfony-version
              run: |
                  composer remove --dev friendsofphp/php-cs-fixer
                  composer require symfony/options-resolver:${{ matrix.symfony-version }} --no-interaction --no-update
                  composer update --no-interaction --no-progress --no-suggest
            - name: "Install dependencies (lowest dependencies) with composer"
              if: matrix.composer-flags
              run: |
                  composer update ${{ matrix.composer-flags }} --no-interaction --no-progress --no-suggest
            - name: "Run tests with phpunit/phpunit"
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[self]=1'
              run: vendor/bin/simple-phpunit
    codecov:
        name: "Code coverage"
        runs-on: ubuntu-latest
        env:
            XDEBUG_MODE: 'coverage'
        strategy:
            matrix:
                include:
                    - php-version: 8.1
                      symfony-version: 6.0.*
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: xdebug
                  php-version: ${{ matrix.php-version }}
            - name: "Install dependencies with composer"
              run: |
                  composer remove --dev friendsofphp/php-cs-fixer
                  composer require symfony/options-resolver:${{ matrix.symfony-version }} --no-interaction --no-update
                  composer update --no-interaction --no-progress --no-suggest
            - name: "Run tests with phpunit/phpunit"
              run: |
                  vendor/bin/simple-phpunit --coverage-text
