name: CI

on:
    pull_request:
    push:
        branches:
            - "master"

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: 8.3

            - name: "Install Dependencies with Composer"
              uses: ramsey/composer-install@v2

            - name: "Run PHPStan"
              run: |
                  vendor/bin/simple-phpunit --version
                  vendor/bin/phpstan analyse --error-format=github

    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: 8.3
                  tools: cs2pr

            - name: "Install Dependencies with Composer"
              uses: ramsey/composer-install@v2

            - name: "Run PHP-CS-Fixer"
              run: vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dependencies: ['highest']
                php-version: ['7.4', '8.0', '8.1', '8.2', '8.3']
                include:
                    - php-version: 7.4
                      dependencies: 'lowest'
                    - php-version: 8.0
                      dependencies: 'lowest'
                    - php-version: 8.1
                      dependencies: 'lowest'
                    - php-version: 8.2
                      dependencies: 'lowest'
                    - php-version: 8.3
                      dependencies: 'lowest'
                    - php-version: 8.2
                      symfony-version: 6.3.*
                    - php-version: 8.2
                      symfony-version: 6.4.*
                    - php-version: 8.3
                      symfony-version: 6.3.*
                    - php-version: 8.3
                      symfony-version: 6.4.*
                    - php-version: 8.3
                      symfony-version: 7.0.*
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: flex
                  coverage: none

            - name: "Install Dependencies with Composer"
              uses: ramsey/composer-install@v2
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
              with:
                  composer-options: "--optimize-autoloader"
                  dependency-versions: "${{ matrix.dependencies }}"

            - name: "Run tests with PHPUnit"
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[self]=1'
              run: vendor/bin/simple-phpunit

    codecov:
        name: "Code coverage"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: pcov
                  php-version: 8.3

            - name: "Install Dependencies with Composer"
              uses: ramsey/composer-install@v2

            - name: "Run tests with PHPUnit and collect coverage"
              run: php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~vendor~" vendor/bin/simple-phpunit --colors=always --coverage-text -vvv
